// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class ScoreModuleBindings
    {
        readonly ICloudCodeService k_Service;
        public ScoreModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task AddScore(int score)
        {
            await k_Service.CallModuleEndpointAsync(
                "API",
                "AddScore",
                new Dictionary<string, object>()
                {
                    {"score", score},
                });
        }

        public async Task InitializeCloudSave()
        {
            await k_Service.CallModuleEndpointAsync(
                "API",
                "InitializeCloudSave",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
