// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class CloudSaveBindings
    {
        readonly ICloudCodeService k_Service;
        public CloudSaveBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task PUT_PlayerScore(int score)
        {
            await k_Service.CallModuleEndpointAsync(
                "PlayerScoreAPI",
                "PUT_PlayerScore",
                new Dictionary<string, object>()
                {
                    {"score", score},
                });
        }

        public async Task PUT_PlayerCharacter(int characterIndex)
        {
            await k_Service.CallModuleEndpointAsync(
                "PlayerScoreAPI",
                "PUT_PlayerCharacter",
                new Dictionary<string, object>()
                {
                    {"characterIndex", characterIndex},
                });
        }

        public async Task PUT_Character(string characterName)
        {
            await k_Service.CallModuleEndpointAsync(
                "PlayerScoreAPI",
                "PUT_Character",
                new Dictionary<string, object>()
                {
                    {"characterName", characterName},
                });
        }

        public async Task PUT_PlayerData(int score, int characterIndex, string characterName)
        {
            await k_Service.CallModuleEndpointAsync(
                "PlayerScoreAPI",
                "PUT_PlayerData",
                new Dictionary<string, object>()
                {
                    {"score", score},
                    {"characterIndex", characterIndex},
                    {"characterName", characterName},
                });
        }

        public async Task<PlayerScoreApiModule.PlayerData> GET_PlayerData()
        {
            return await k_Service.CallModuleEndpointAsync<PlayerScoreApiModule.PlayerData>(
                "PlayerScoreAPI",
                "GET_PlayerData",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task DELETE_PlayerData()
        {
            await k_Service.CallModuleEndpointAsync(
                "PlayerScoreAPI",
                "DELETE_PlayerData",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
