// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.PlayerScoreApiModule
{
    public partial class PlayerData
    {
        public int Score;
        public int LastUsedCharacterIndex;
        public string lastUsedCharacterName;

        [Preserve]
        public PlayerData ()
        {
        }
    }
}